name: Tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jest run
        run: |
          npm install
          npm run test
